resolver: lts-24.59

extra-lib-dirs:
    - ../chusql-core/storage/target/release

packages:
    - .
    - ../chusql-core/engine
    - ../chusql-server
    - ../chusql-core/model
    - ../chusql-interface
